Select
comment_id,
author_channel_id,
author_name,
case when (victim_channels >=2) then 1 else 0 end as is_author_a_troll,
case when (victim_channels is null) then 0 else victim_channels end as victim_channels,
case when (toxic_comments_by_author is null) then 0 else toxic_comments_by_author end as toxic_comments_by_author,
video_id,
channel_id,
comment_date,
is_comment_at_night,
comment_hour_of_the_day,
is_female_channel,
is_minority_race,
case when (is_toxicity is null) then 0 else is_toxicity end as is_toxicity,
case when (is_severe_toxicity is null) then 0 else is_severe_toxicity end as is_severe_toxicity,
case when (is_obscene is null) then 0 else is_obscene end as is_obscene,
case when (is_threat is null) then 0 else is_threat end as is_threat,
case when (is_insult is null) then 0 else is_insult end as is_insult,
case when (is_identity_hate is null) then 0 else is_identity_hate end as is_identity_hate,
is_channel_teen,
v_duration_min,
view_count,
like_count,
dislike_count,
text
from `hatespeech-2019.HS_trolls_analysis.Temp_results` 
order by
video_id,
comment_date,
comment_hour_of_the_day 
